server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    root: ${LOG_LEVEL:INFO}
    org.springframework.web: ${WEB_LOG_LEVEL:INFO}
    org.apache.http.wire: INFO
    org.hidetake.stubyaml: ${APP_LOG_LEVEL:INFO}

stub:
  admin-prefix: ${ADMIN-PREFIX:/admin}
  data: ${STUB_DATA:data}
  interval-sec: ${WATCH_INTERVAL:3}
  watcher-enabled: ${WATCH_ENABLED:true}
